### PR TITLE
docs: update template

### LINKED ISSUE #428: BS5 template for pkgdown website
Is there any reason why bs5 has not been enabled?

### LINKED ISSUE #438: contrast of some colors
Observations of the flatly bootswatch theme, valid for both Bootstrap versions.

The link color is too light

image

The version header is too dark

image

I'll make suggestions in my PR (i.e. apply better colors)

### PR DESCRIPTION
**Pull request by maelle**
Fix #428 
Fix #438 

On https://webaim.org/resources/contrastchecker/ I changed the lightness/darkness to get AAA. It's less colorful as a result, maybe other colors could be found that both are darker/lighter but not sadder. :sweat_smile: 

image

### CODE REVIEW

**Comment by krlmlr** [comment]
Thanks, looks good! Please mark ready for review when good, will be auto-merged.

**Comment by maelle** [comment]
I did a bit more work to prevent color changes on hovering (as the color was then not the nicest for contrast). I'm not sure the current choices are the best.

Main links on hovering, wavy underline decoration

image


Nav links on hovering, wavy underline decoration too

image

**Review by hadley — APPROVED** [review]

**Comment by krlmlr** [comment]
Thanks! Can you please apply to the other repositories?

**Comment by maelle** [comment]
@krlmlr it seems wiser to create and use a template package holding the configuration file, or do you prefer only configuration edits?

**Comment by krlmlr** [comment]
A template would be great, thanks!

**Comment by maelle** [comment]
could you please create an empty repo under `r-dbi` and give me write access? It could be called dbitemplate. Thank you!

**Comment by krlmlr** [comment]
Happy to accept a repo transfer for a repo you create 😉

**Pull request merged**
